# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Travel Model Two
tagline:          'Metropolitan Transportation Commission'
url:              http://metropolitantransportationcommission.github.io/travel-model-two
shorturl:         metropolitantransportationcommission.github.io/travel-model-two

author:
  name:           'David Ory'
  url:            https://github.com/DavidOry

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MetropolitanTransportationCommission/travel-model-two/tree/gh-pages

# This is the list of pages to include in the header of the website.
pages_list:       
  Guide: 'guide/'
  Process: 'process/'
  Geographies: 'geographies/'
  Other: 'other/'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
