site_name: Travel Model Two
site_url: http://bayareametro.github.io/travel-model-two/
repo_url: https://github.com/BayAreaMetro/travel-model-two

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes

nav:
- Travel Model Two: 'index.md'
- Guide: 'guide.md'
- Input: 'input.md'
- Process: 'process.md'
- Output: 'output.md'
- Geographies: 'geographies.md'
- Papers: 'papers.md'
- Network QA: 'network_qa.md'

plugins:
  - autorefs
  - mike:

extra:
  version:
    provider: mike
    default: latest
